### ISSUE TITLE
Null pointer exception while creating streamsql context from checkpoint data

### ISSUE THREAD

**Issue by Shasidhar** [Intel-bigdata/spark-streamingsql#13]
```java
java.lang.NullPointerException
	at org.apache.spark.sql.streaming.SchemaDStream.parentStreams$lzycompute(SchemaDStream.scala:75)
	at org.apache.spark.sql.streaming.SchemaDStream.parentStreams(SchemaDStream.scala:70)
	at org.apache.spark.sql.streaming.SchemaDStream.dependencies(SchemaDStream.scala:50)
	at org.apache.spark.streaming.dstream.DStream.setContext(DStream.scala:244)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$setContext$2.apply(DStream.scala:244)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$setContext$2.apply(DStream.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.streaming.dstream.DStream.setContext(DStream.scala:244)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$setContext$1.apply(DStreamGraph.scala:65)
	at org.apache.spark.streaming.DStreamGraph$$anonfun$setContext$1.apply(DStreamGraph.scala:65)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.streaming.DStreamGraph.setContext(DStreamGraph.scala:65)
	at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:136)
	at org.apache.spark.streaming.StreamingContext$$anonfun$getOrCreate$1.apply(StreamingContext.scala:633)
	at org.apache.spark.streaming.StreamingContext$$anonfun$getOrCreate$1.apply(StreamingContext.scala:633)
	at scala.Option.map(Option.scala:145)
	at org.apache.spark.streaming.StreamingContext$.getOrCreate(StreamingContext.scala:633)
	at org.apache.spark.streaming.api.java.JavaStreamingContext$.getOrCreate(JavaStreamingContext.scala:709)
	at org.apache.spark.streaming.api.java.JavaStreamingContext.getOrCreate(JavaStreamingContext.scala
```

**Comment by Shasidhar** [comment]
Any idea what is going wrong here?

**Comment by chenghao-intel** [comment]
@Shasidhar can you give some detail info how do you run into this exception?

**Comment by Shasidhar** [comment]
```java
private class JavaStreamingContextFactoryInner implements JavaStreamingContextFactory
	{

		@SuppressWarnings({ "unchecked", "rawtypes" })
		@Override
		public JavaStreamingContext create()
		{
			final SparkStreamingConfig streamingConfig = actionalStreamingEngineConfig
					.getSparkStreamingConfig();

			final SparkConf conf = setupSparkConf(streamingConfig);

			final JavaStreamingContext jssc = new JavaStreamingContext(conf,
					Durations.seconds(streamingConfig.getBatchDuration()));

			jssc.checkpoint(streamingConfig.getSparkCheckpointDir());

			// add classpath jars to spark context
			final List<String> classPathJars = getClassPathJars();
			final JavaSparkContext sparkContext = jssc.sparkContext();
			for (final String jar : classPathJars)
			{
				sparkContext.addJar(jar);
			}
		    	HiveContext sqlContext = new HiveContext(sparkContext.sc());
		    	StreamSQLContext streamSQLContext = new StreamSQLContext(jssc.ssc(),sqlContext);

		    	sparkRunTimeContext = new SparkRunTimeContext(jssc, actionalStreamingEngineConfig,streamSQLContext);
			// receive the data and create the stream
			final JavaDStream inputStream = streamingReceiver.receiveStream(sparkRunTimeContext);

			// process: filter, transform and aggregate the stream
			final List<ActionalStream> outputStream = streamingProcessor.process(inputStream,
					sparkRunTimeContext);

			// persist the processed streams
			streamingStore.persistStreams(outputStream, sparkRunTimeContext);

			return jssc;
		}
	}
```

This is the factory method where the creation of Streamingsqlcontext happens. Once we create it we pass it to the descending methods.

**Comment by wlwgcdxc** [comment]
Hi,I have a question when compile the spark-streamingsql-master.
The following is  the error stack:

[error] /opt/xcdong/spark-streamingsql-master/src/main/scala/org/apache/spark/sql/streaming/SchemaDStream.scala:64: not found: type CreateTableAsSelect
[error]     case _: InsertIntoTable | _: CreateTableAsSelect[_] | _: WriteToFile =>
[error]                                  ^
[error] /opt/xcdong/spark-streamingsql-master/src/main/scala/org/apache/spark/sql/streaming/StreamSQLContext.scala:63: type mismatch;
[error]  found   : org.apache.spark.sql.types.StructType
[error]  required: Seq[org.apache.spark.sql.types.DataType]
[error]     val rowStream = stream.transform(rdd => RDDConversions.productToRowRdd(rdd, schema))
[error]                                                                                 ^
[error] /opt/xcdong/spark-streamingsql-master/src/main/scala/org/apache/spark/sql/streaming/StreamSQLParser.scala:49: not enough arguments for method apply: (input: String, exceptionOnError: Boolean)Option[org.apache.spark.sql.catalyst.plans.logical.LogicalPlan] in class StreamSQLParser.
[error] Unspecified value parameter exceptionOnError.
[error]       Some(apply(input))
[error]                 ^
[error] three errors found
[error] (compile:compile) Compilation failed
[error] Total time: 6 s, completed Dec 21, 2015 4:49:07 AM

What's wrong with it? ^_^
Thanks.

**Comment by adrian-wang** [comment]
@wlwgcdxc Can you start a new issue? I think that's not related to this.
