### ISSUE TITLE
WARN TaskSetManager: Lost task 0.0 in stage 11.0 (TID 871, xa36502.eng.platformlab.ibm.com): java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.sql.types.UTF8String

### ISSUE THREAD

**Issue by wlwgcdxc** [Intel-bigdata/spark-streamingsql#17]
HI, I got a exception which is ClassCastException: java.lang.String cannot be cast to org.apache.spark.sql.types.UTF8String.

My job ran under the spark shell mode using 1.4.1 version.
And the related code is following:

import org.apache.spark.sql.{SQLContext, Row}
import org.apache.spark.sql.streaming.StreamSQLContext
import org.apache.spark.sql.streaming.sources.MessageToRowConverter
import org.apache.spark.streaming.{Duration, StreamingContext}
import org.apache.spark.SparkConf
import org.apache.spark.streaming.kafka._

class MessageDelimiter extends MessageToRowConverter {
  def toRow(msg: String): Row = Row(msg)
}

val ssc = new StreamingContext(sc, Duration(3000))
val streamSqlContext = new StreamSQLContext(ssc, new SQLContext(sc))
    
streamSqlContext.command(
   """
   |CREATE TEMPORARY TABLE t_kafka (
   |  word string
   |)
   |USING org.apache.spark.sql.streaming.sources.KafkaSource
   |OPTIONS(
   |  zkQuorum "localhost:2181",
   |  groupId  "test",
   |  topics   "test1:1",
   |  messageToRow "org.apache.spark.sql.streaming.examples.MessageDelimiter")
   """.stripMargin)

val rdd = streamSqlContext.sql(
   """
   |SELECT t.word, COUNT(t.word)
   |FROM (SELECT * FROM t_kafka) OVER (WINDOW '9' SECONDS, SLIDE '3' SECONDS) AS t
   |GROUP BY t.word
   """.stripMargin).foreachRDD { r => r.foreach(println) }

ssc.start()
ssc.awaitTermination()

the error stack is :
15/12/22 13:30:42 WARN TaskSetManager: Lost task 0.0 in stage 67.0 (TID 6471, xa36502.eng.platformlab.ibm.com): java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.sql.types.UTF8String
        at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:334)
        at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:227)
        at org.apache.spark.sql.execution.Serializer2SerializationStream.writeKey(SparkSqlSerializer2.scala:65)
        at org.apache.spark.storage.DiskBlockObjectWriter.write(BlockObjectWriter.scala:206)
        at org.apache.spark.util.collection.WritablePartitionedIterator$$anon$3.writeNext(WritablePartitionedPairCollection.scala:104)
        at org.apache.spark.util.collection.ExternalSorter.spillToPartitionFiles(ExternalSorter.scala:375)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:208)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:70)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

what is wrong with it? ^_^
Thank you very much.

**Comment by adrian-wang** [comment]
class MessageDelimiter extends MessageToRowConverter {
      def toRow(msg: String): Row = Row(msg)
    }

maybe you need to put `UTF8String` in a `Row` object here.

**Comment by wlwgcdxc** [comment]
explicit cast? Let me try.

**Comment by adrian-wang** [comment]
try `UTF8String.fromString("....................")`

**Comment by wlwgcdxc** [comment]
error: value fromString is not a member of object org.apache.spark.sql.types.UTF8String
         def toRow(msg: String): Row = Row(UTF8String.fromString(msg))

**Comment by wlwgcdxc** [comment]
error: object types is not a member of package org.apache.spark.unsafe
         def toRow(msg: String): Row = Row(org.apache.spark.unsafe.types.UTF8String.fromString(msg))
........
Maybe my pakage imported is error.
Thank you very much. I continue to think...

**Comment by adrian-wang** [comment]
oh, I get this, the interface of `UTF8String` is different as Spark 1.4.1.
try `UTF8String.set(msg)`
and use `org.apache.spark.sql.types.UTF8String`

**Comment by wlwgcdxc** [comment]
error: value set is not a member of object org.apache.spark.sql.types.UTF8String
         def toRow(msg: String): Row = Row(UTF8String.set(msg))
........

**Comment by adrian-wang** [comment]
...
should be 
`UTF8String.apply(msg)`

**Comment by wlwgcdxc** [comment]
scala> import org.apache.spark.sql.types.UTF8String
import org.apache.spark.sql.types.UTF8String

scala> class MessageDelimiter extends MessageToRowConverter {
     |   def toRow(msg: String): Row = Row(UTF8String.apply(msg))
     | }
defined class MessageDelimiter
......
But that exception is still 
15/12/22 15:09:45 WARN TaskSetManager: Lost task 0.0 in stage 15.0 (TID 1271, xa36502.eng.platformlab.ibm.com): java.lang.ClassCastException: java.lang.String cannot be cast to org.apache.spark.sql.types.UTF8String
        at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:334)
        at org.apache.spark.sql.execution.SparkSqlSerializer2$$anonfun$createSerializationFunction$1.apply(SparkSqlSerializer2.scala:227)
        at org.apache.spark.sql.execution.Serializer2SerializationStream.writeKey(SparkSqlSerializer2.scala:65)
        at org.apache.spark.storage.DiskBlockObjectWriter.write(BlockObjectWriter.scala:206)
        at org.apache.spark.util.collection.WritablePartitionedIterator$$anon$3.writeNext(WritablePartitionedPairCollection.scala:104)
        at org.apache.spark.util.collection.ExternalSorter.spillToPartitionFiles(ExternalSorter.scala:375)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:208)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:70)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

15/12/22 15:09:46 ERROR TaskSetManager: Task 0 in stage 15.0 failed 4 times; aborting job
15/12/22 15:09:46 ERROR JobScheduler: Error running job streaming job 1450768185000 ms.0

**Comment by wlwgcdxc** [comment]
what can I do?
.............
I don't even find the UTF8String code in spark source code. And the code which is \sql\catalyst\src\main\scala\org\apache\spark\sql\types\StringType.scala should be related, but too little.

**Comment by adrian-wang** [comment]
That is in \sql\catalyst\src\main\scala\org\apache\spark\sql\types\UTF8String.scala as of Spark 1.4.1

**Comment by wlwgcdxc** [comment]
I don't have this scala file. Maybe my cluster have some question.

**Comment by adrian-wang** [comment]
So your cluster is not running Spark 1.4.1

**Comment by wlwgcdxc** [comment]
I'm sure my cluster is running Spark 1.4.1. But that file is not in my source code and I don't konw why.
......

**Comment by wlwgcdxc** [comment]
Hi, sir.
Did you run this code which is spark-streamingsql/src/main/scala/org/apache/spark/sql/streaming/examples/KafkaDDL.scala. And have no question?

**Comment by adrian-wang** [comment]
@chenghao-intel Could you take a look at this?

**Comment by wlwgcdxc** [comment]
@adrian-wang ,thank you very much ^_^

**Comment by chenghao-intel** [comment]
Sorry for late reply, we will look into it.

**Comment by wlwgcdxc** [comment]
It doesn't matter. Thank you.^_^

**Comment by zhichao-li** [comment]
@wlwgcdxc  Wondering which branch are you base on? The master branch of `StreamSQL` only support 1.3.0.  I think you should use branch `for_spark_1.4.1` same as your cluster version.

**Comment by adrian-wang** [comment]
@zhichao-li master does support 1.4.1

**Comment by zhichao-li** [comment]
yeah, master only base on 1.3.0, but the branch `for_spark_1.4.1` of StreamSQL do support spark `1.4.1`

**Comment by chenghao-intel** [comment]
Sorry about the confusing, as I forgot to update the README.
