### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/CreateTableAsSelect

### ISSUE THREAD

**Issue by pratikasarda** [Intel-bigdata/spark-streamingsql#32]
I made the jar of project and trying to run my own defined streaming sql program(using hive context instead of sqlContext) Im getting following exception when I registered the table.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/CreateTableAsSelect
        at org.apache.spark.sql.streaming.SchemaDStream.<init>(SchemaDStream.scala:64)
        at org.apache.spark.sql.streaming.SchemaDStream.<init>(SchemaDStream.scala:48)
        at org.apache.spark.sql.streaming.StreamSQLContext.createSchemaDStream(StreamSQLContext.scala:64)
        at com.yash.testcep.OutliersFinder$.main(OutliersFinder.scala:40)
        at com.yash.testcep.OutliersFinder.main(OutliersFinder.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.CreateTableAsSelect
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by adrian-wang** [comment]
This error mostly results from a mismatched spark version. Could you provide more details?

**Comment by pratikasarda** [comment]
I am using spark version 1.5.1
